apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cloudzero-certificate.labels" . | nindent 4 }}
  name: {{ include "cloudzero-certificate.secretName" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- include "cloudzero-certificate.genCerts" . | nindent 2 }}
