apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudzero-prometheus-config # todo naming
  namespace: default
data:
  prometheus.yml: |-
    global:
      scrape_interval: 60s
    scrape_configs:
      - job_name: 'cz-kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: node
          - source_labels: [__address__]
            target_label: __address__
            regex: (.*)
            replacement: $1:9100
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: kubernetes_node_name
        metrics_path: /metrics
        honor_labels: true
        scheme: http
        params:
          format: ['prometheus']
      - job_name: 'cz-kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: '.*'
            target_label: container
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            replacement: $1
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: ${1}
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
        metrics_path: /metrics
        honor_labels: true
        scheme: http
        params:
          format: ['prometheus']
