apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.configMapName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
data:
  prometheus.yml: |-
  {{- if .Values.promethuesConfig.configOverride }}
  {{ .Values.promethuesConfig.configOverride | nindent 4 }}
  {{- else }}
    global:
      scrape_interval: 60s
    scrape_configs:
      - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        job_name: cz-nodes-cadvisor
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - replacement: kubernetes.default.svc:443
          target_label: __address__
        - regex: (.+)
          replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
          source_labels:
          - __meta_kubernetes_node_name
          target_label: __metrics_path__
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
      - job_name: cz-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: '.*'
            target_label: container
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            replacement: $1
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: ${1}
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
        metrics_path: /metrics
        honor_labels: true
        scheme: http
        params:
          format: ['prometheus']
    remote_write:
      - url: 'https://{{ .Values.cloudzero.host }}/v1/container-metrics?cluster_name={{.Values.cloudzero.cluster_name}}&cloud_account_id={{.Values.cloudzero.cloud_account_id}}'
        authorization:
          credentials_file: /etc/config/prometheus/secrets/value
        write_relabel_configs:
          - source_labels: [__name__]
            regex: "^({{ join "|" .Values.cloudzero.metrics }})$"
            action: keep
        metadata_config:
          send: false
    {{- end}}
