apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "insights-controller.labels" . | nindent 4 }}
  name: {{ include "insights-controller.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.server.configMap.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  server-config.yaml: |-
    {{- if .Values.cloudAccountId }}
    cloud_account_id: {{ .Values.cloudAccountId }}
    {{- end }}
    {{- if .Values.region }}
    region: {{ .Values.region }}
    {{- end }}
    {{- if .Values.clusterName }}
    cluster_name: {{ .Values.clusterName }}
    {{- end }}
    {{- if .Values.host }}
    host: {{ .Values.host }}
    {{- end }}
    remote_write:
      send_interval: 1m
      max_bytes_per_send: 500000
      send_timeout: 10s
      max_retries: 3
    k8s_client:
      timeout: 30s
    database:
      retention_time: 24h
      cleanup_interval: 3h
      batch_update_size: 500
    {{- with .Values.server.tls }}
    certificate:
      key: {{ .mountPath }}/tls.key
      cert: {{ .mountPath }}/tls.crt
    {{- end }}
    api_key_path: {{ .Values.server.serverConfig.containerSecretFilePath }}/{{ .Values.server.serverConfig.containerSecretFileName }}
    server:
      port: {{ .Values.server.serverConfig.port }}
      read_timeout: {{ .Values.server.serverConfig.read_timeout }}
      write_timeout: {{ .Values.server.serverConfig.write_timeout }}
      idle_timeout: {{ .Values.server.serverConfig.idle_timeout }}
    filters:
      labels:
        {{- .Values.labels | toYaml | nindent 8 }}
      annotations:
        {{- .Values.annotations | toYaml | nindent 8 }}
      
