# -- CloudZero host to send metrics to.
host: dev-api.cloudzero.com
# -- Account ID of the account the cluster is running in. This must be a string - even if it is a number in your system.
cloudAccountId: '975482786146'
# -- Name of the clusters.
clusterName: danm
# -- Region the cluster is running in.
region: us-east-1
# -- CloudZero API key. Required if useExistingSecret is false.
apiKey: null
# -- If set, the agent will use the API key in this Secret to authenticate with CloudZero.
existingSecretName: cloudzero-agent-with-ui-api-key-existing

# special values for danm cluster - ignore these
server:
  containerSecretFileName: cz-api-key

# label and annotation configuration:
tags:
  enabled: true
  server:
    containerSecretFileName: cz-api-key
  # -- By default, a ValidatingAdmissionWebhook will be deployed that records all created labels and annotations
  labels:
    # -- This value MUST be set to either true or false. The installation will fail otherwise
    enabled:
    # -- This value MUST be set to a list of regular expressions which wil lbe used to gather labels from pods, deployments, statefulsets, daemonsets, cronjobs, jobs, nodes, and namespaces
    patterns:
      # - '.*' # -- This option enables gathering ALL labels from the above resources. Use with caution, as the number of labels can be large.
  annotations:
    # -- By default, the gathering of annotations is not enabled. To enable, set this field to true
    enabled: false
    patterns:
      - '.*'

  # special values for danm cluster - ignore these
  existingSecretName: cloudzero-agent-with-ui-api-key-existing
  host: dev-api.cloudzero.com
  cloudAccountId: '975482786146'
  clusterName: danm
  region: us-east-1
