{{/*
Grafana Alloy River Configuration Helpers

This template file contains helpers for generating Grafana Alloy River configuration.
Alloy uses the River configuration language instead of Prometheus YAML, so these helpers
translate the chart's configuration into River format.

River is a declarative configuration language that uses components and data flow to define
observability pipelines. Components are connected via references to create processing chains.

For more information on River, see:
https://grafana.com/docs/alloy/latest/reference/river/
*/}}

{{/*
Generate complete Alloy River configuration

This is the main entry point that generates the full River configuration for Alloy.
It includes:
- Discovery components for Kubernetes service discovery
- Scrape components for metric collection
- Remote write components for forwarding to aggregator

Usage: {{ include "cloudzero-agent.alloy.riverConfig" . }}
*/}}
{{- define "cloudzero-agent.alloy.riverConfig" -}}
// CloudZero Agent - Alloy Configuration
// Generated by Helm chart version {{ .Chart.Version }}

{{- if .Values.prometheusConfig.scrapeJobs.kubeStateMetrics.enabled }}
{{- include "cloudzero-agent.alloy.scrapeKubeStateMetrics" . }}
{{- end }}

{{- if .Values.prometheusConfig.scrapeJobs.cadvisor.enabled }}
{{- include "cloudzero-agent.alloy.scrapeCAdvisor" . }}
{{- end }}

{{- if .Values.insightsController.enabled }}
{{- include "cloudzero-agent.alloy.scrapeWebhook" . }}
{{- end }}

{{- if .Values.prometheusConfig.scrapeJobs.aggregator.enabled }}
{{- include "cloudzero-agent.alloy.scrapeAggregator" . }}
{{- end }}

{{- if .Values.prometheusConfig.scrapeJobs.prometheus.enabled }}
{{- include "cloudzero-agent.alloy.scrapeAlloy" . }}
{{- end }}

// Remote write to CloudZero aggregator
{{- include "cloudzero-agent.alloy.remoteWrite" . }}
{{- end -}}

{{/*
Alloy Kube-State-Metrics Scrape Job

Generates River configuration for scraping kube-state-metrics.
Translates the Prometheus scrape job into Alloy's discovery + scrape pattern.

Usage: {{ include "cloudzero-agent.alloy.scrapeKubeStateMetrics" . }}
*/}}
{{- define "cloudzero-agent.alloy.scrapeKubeStateMetrics" -}}
// Kube State Metrics Scrape Job
// Provides information about Kubernetes object configuration and state

prometheus.scrape "kube_state_metrics" {
  targets = [{
    __address__ = "{{ include "cloudzero-agent.kubeStateMetrics.kubeStateMetricsSvcTargetName" . }}",
  }]
  forward_to = [prometheus.relabel.kube_state_metrics_metrics.receiver]
  scrape_interval = "{{ .Values.prometheusConfig.scrapeJobs.kubeStateMetrics.scrapeInterval }}"

  clustering {
    enabled = true
  }
}

// Filter metrics - keep only CloudZero cost metrics
prometheus.relabel "kube_state_metrics_metrics" {
  forward_to = [prometheus.relabel.kube_state_metrics_labels.receiver]

  // Keep only specific metric names
  rule {
    source_labels = ["__name__"]
    regex         = "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).kubeMetrics }})$"
    action        = "keep"
  }
}

// Filter labels - keep only relevant labels
prometheus.relabel "kube_state_metrics_labels" {
  forward_to = [prometheus.remote_write.cloudzero.receiver]

  // Keep only specific labels
  rule {
    regex  = "^({{ include "cloudzero-agent.requiredMetricLabels" . }})$"
    action = "labelkeep"
  }
}
{{- end -}}

{{/*
Alloy cAdvisor Scrape Job

Generates River configuration for scraping cAdvisor metrics from Kubernetes nodes.

Usage: {{ include "cloudzero-agent.alloy.scrapeCAdvisor" . }}
*/}}
{{- define "cloudzero-agent.alloy.scrapeCAdvisor" -}}
// cAdvisor Scrape Job
// Collects container resource usage metrics

discovery.kubernetes "cadvisor" {
  role = "node"
}

prometheus.scrape "cadvisor" {
  targets    = discovery.kubernetes.cadvisor.targets
  forward_to = [prometheus.relabel.cadvisor.receiver]
  scrape_interval = "{{ .Values.prometheusConfig.scrapeJobs.cadvisor.scrapeInterval }}"
  metrics_path = "/metrics/cadvisor"
  scheme = "https"

  bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"

  tls_config {
    ca_file              = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    insecure_skip_verify = false
  }

  clustering {
    enabled = true
  }
}

// Filter cAdvisor metrics - keep only CloudZero cost metrics
prometheus.relabel "cadvisor" {
  forward_to = [prometheus.remote_write.cloudzero.receiver]

  // Keep only specific metrics needed for cost allocation
  rule {
    source_labels = ["__name__"]
    regex         = "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).containerMetrics }})$"
    action        = "keep"
  }

  // Keep only required labels
  rule {
    regex  = "^({{ include "cloudzero-agent.requiredMetricLabels" . }})$"
    action = "labelkeep"
  }

  // Map node name for cost allocation
  rule {
    source_labels = ["__meta_kubernetes_node_name"]
    target_label  = "node"
  }
}
{{- end -}}

{{/*
Alloy Webhook Scrape Job

Generates River configuration for scraping CloudZero webhook server metrics.

Usage: {{ include "cloudzero-agent.alloy.scrapeWebhook" . }}
*/}}
{{- define "cloudzero-agent.alloy.scrapeWebhook" -}}
// CloudZero Webhook Scrape Job
// Monitors webhook server performance and health

discovery.kubernetes "webhook" {
  role = "endpoints"

  selectors {
    role  = "endpoints"
    field = "metadata.name={{ include "cloudzero-agent.serviceName" . }}"
  }
}

prometheus.scrape "webhook" {
  targets    = discovery.kubernetes.webhook.targets
  forward_to = [prometheus.relabel.webhook.receiver]
  scrape_interval = "{{ .Values.prometheusConfig.scrapeJobs.prometheus.scrapeInterval }}"
  scheme = "https"

  tls_config {
    insecure_skip_verify = true
  }

  clustering {
    enabled = true
  }
}

// Filter webhook metrics - keep only CloudZero observability metrics
prometheus.relabel "webhook" {
  forward_to = [prometheus.remote_write.cloudzero.receiver]

  // Keep only insights/webhook metrics
  rule {
    source_labels = ["__name__"]
    regex         = "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).insightsMetrics }})$"
    action        = "keep"
  }
}
{{- end -}}

{{/*
Alloy Aggregator Scrape Job

Generates River configuration for scraping CloudZero aggregator metrics.

Usage: {{ include "cloudzero-agent.alloy.scrapeAggregator" . }}
*/}}
{{- define "cloudzero-agent.alloy.scrapeAggregator" -}}
// CloudZero Aggregator Scrape Job
// Monitors aggregator performance and health

prometheus.scrape "aggregator" {
  targets = [{
    __address__ = "{{ include "cloudzero-agent.aggregator.name" . }}:{{ .Values.aggregator.shipper.port }}",
  }]
  forward_to = [prometheus.relabel.aggregator.receiver]
  scrape_interval = "{{ .Values.prometheusConfig.scrapeJobs.aggregator.scrapeInterval }}"

  clustering {
    enabled = true
  }
}

// Filter aggregator metrics - keep cost and observability metrics
prometheus.relabel "aggregator" {
  forward_to = [prometheus.remote_write.cloudzero.receiver]

  // Keep metrics matching the combined cost + observability filter
  rule {
    source_labels = ["__name__"]
    regex         = "{{ include "cloudzero-agent.generateMetricNameFilterRegex" .Values }}"
    action        = "keep"
  }
}
{{- end -}}

{{/*
Alloy Self-Scrape Job

Generates River configuration for Alloy to scrape its own metrics.

Usage: {{ include "cloudzero-agent.alloy.scrapeAlloy" . }}
*/}}
{{- define "cloudzero-agent.alloy.scrapeAlloy" -}}
// Alloy Self-Scrape Job
// Monitors Alloy's own performance metrics

discovery.relabel "alloy" {
  targets = [{
    __address__ = "localhost:9090",
  }]

  rule {
    target_label = "job"
    replacement  = "alloy"
  }

  rule {
    target_label = "instance"
    replacement  = env("HOSTNAME")
  }
}

prometheus.scrape "alloy" {
  targets    = discovery.relabel.alloy.output
  forward_to = [prometheus.relabel.alloy.receiver]
  scrape_interval = "{{ .Values.prometheusConfig.scrapeJobs.prometheus.scrapeInterval }}"

  clustering {
    enabled = true
  }
}

// Filter Alloy metrics - keep only Prometheus operational metrics
prometheus.relabel "alloy" {
  forward_to = [prometheus.remote_write.cloudzero.receiver]

  // Keep only Prometheus metrics needed for monitoring
  rule {
    source_labels = ["__name__"]
    regex         = "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).prometheusMetrics }})$"
    action        = "keep"
  }
}
{{- end -}}

{{/*
Alloy Remote Write Configuration

Generates River configuration for remote_write to CloudZero aggregator.
This is the sink where all scraped metrics are forwarded.

Usage: {{ include "cloudzero-agent.alloy.remoteWrite" . }}
*/}}
{{- define "cloudzero-agent.alloy.remoteWrite" -}}
// Remote Write to CloudZero Aggregator
prometheus.remote_write "cloudzero" {
  endpoint {
    url = "http://{{ include "cloudzero-agent.aggregator.name" . }}.{{ .Release.Namespace }}.svc.cluster.local/collector"

    // Metadata sends metric type information but is not needed for cost metrics
    send_exemplars    = false
    send_native_histograms = false

    queue_config {
      capacity          = 10000
      max_shards        = 10
      min_shards        = 1
      max_samples_per_send = 5000
      batch_send_deadline  = "5s"
      min_backoff          = "30ms"
      max_backoff          = "5s"
    }
  }
}
{{- end -}}
