{{- if eq (include "cloudzero-agent.Values.components.agent.mode" .) "federated" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "server"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.agent.labels
        .Values.components.agent.federatedNode.labels
      )
    ) | nindent 2 }}
  name: {{ .Release.Name }}-daemonset-cm
  namespace: {{ include "cloudzero-agent.namespace" . }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.prometheusConfig.configMapAnnotations
        .Values.components.agent.annotations
        .Values.components.agent.federatedNode.annotations
      )
    ) | nindent 2 }}
data:
  prometheus.yml.in: |-
    {{- if and (ne (include "cloudzero-agent.Values.components.agent.mode" .) "federated") .Values.prometheusConfig.configOverride }}
    {{ .Values.prometheusConfig.configOverride | nindent 4 }}
    {{- else }}
    global:
      scrape_interval: {{ .Values.prometheusConfig.globalScrapeInterval }}

    scrape_configs:
      {{- if .Values.prometheusConfig.scrapeJobs.cadvisor.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeCAdvisor" (dict "root" . "scrapeLocalNodeOnly" true) | nindent 6 }}
      {{- end }}{{/* End cadvisor scrape job */}}

      {{- if .Values.prometheusConfig.scrapeJobs.prometheus.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapePrometheus" . | nindent 6 }}
      {{- end }}
    {{- end}}

    {{- include "cloudzero-agent.aggregator.remoteWrite" . | nindent 4 }}
{{- end }}
