apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "cloudzero-agent.generateAnnotations" .Values.server.deploymentAnnotations | nindent 2 }}
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  {{- include "cloudzero-agent.generateAnnotations" .Values.defaults.annotations | nindent 2 }}
  name: {{ template "cloudzero-agent.server.fullname" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "cloudzero-agent.server.matchLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- include "cloudzero-agent.generateAnnotations" .Values.server.podAnnotations | nindent 8 }}
      labels:
        {{- include "cloudzero-agent.server.labels" . | nindent 8 }}
        {{- if .Values.server.podLabels}}
        {{ toYaml .Values.server.podLabels | nindent 8 }}
        {{- end}}
    spec:
      {{- include "cloudzero-agent.generatePriorityClassName" (.Values.defaults.priorityClassName | default .Values.server.priorityClassName) | nindent 6 }}
      serviceAccountName: {{ template "cloudzero-agent.serviceAccountName" . }}
      initContainers:
        - name: {{ .Values.validator.name }}-copy
          {{- include "cloudzero-agent.generateImage" (dict "defaults" .Values.defaults.image "image" .Values.components.agent.image "compat" .Values.validator.image) | nindent 10 }}
          env:
            {{- include "cloudzero-agent.validatorEnv" . | nindent 12 }}
          command:
            - /app/cloudzero-agent-validator
            - install
            - --destination
            - /checks/bin/cloudzero-agent-validator
          {{- with .Values.validator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- include "cloudzero-agent.apiKeyVolumeMount" . | nindent 12 }}
            - name: lifecycle-volume
              mountPath: /checks/bin/
            - name: validator-config-volume
              mountPath: /checks/config/
        - name: {{ .Values.validator.name }}-run
          {{- include "cloudzero-agent.generateImage" (dict "defaults" .Values.defaults.image "image" .Values.components.agent.image "compat" .Values.validator.image) | nindent 10 }}
          env:
            {{- include "cloudzero-agent.validatorEnv" . | nindent 12 }}
          command:
            - /checks/bin/cloudzero-agent-validator
            - diagnose
            - pre-start
            - -f
            - /checks/config/validator.yml
          {{- with .Values.validator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- include "cloudzero-agent.apiKeyVolumeMount" . | nindent 12 }}
            - name: lifecycle-volume
              mountPath: /checks/bin/
            - name: validator-config-volume
              mountPath: /checks/config/
      containers:
        {{- if .Values.configmapReload.prometheus.enabled }}
        - name: {{ template "cloudzero-agent.name" . }}-{{ .Values.server.name }}-configmap-reload
          {{- include "cloudzero-agent.generateImage" (dict "defaults" .Values.defaults.image "image" .Values.components.prometheusReloader.image "compat" .Values.configmapReload.prometheus.image) | nindent 10 }}
          args:
            - --watched-dir=/etc/config
            - --reload-url=http://127.0.0.1:9090/-/reload
            - --listen-address=:8080
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
            successThreshold: 1
          {{- with .Values.configmapReload.prometheus.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
        {{- end }}
        - name: {{ template "cloudzero-agent.name" . }}-server
          {{/* This is a little special because we want to fall back on the .Chart.AppVersion */}}
          {{- include "cloudzero-agent.generateImage" (dict "defaults" .Values.defaults.image "image" .Values.components.prometheus.image "compat" (dict "repository" .Values.server.image.repository "tag" (.Values.server.image.tag | default .Values.components.prometheus.image.tag | default .Chart.AppVersion) "digest" .Values.server.image.digest "pullPolicy" .Values.server.image.pullPolicy)) | nindent 10 }}
          {{- if .Values.server.env }}
          env:
{{ toYaml .Values.server.env | indent 12}}
            {{- include "cloudzero-agent.validatorEnv" . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /checks/cloudzero-agent-validator
                  - diagnose
                  - post-start
                  - -f
                  - /checks/app/config/validator.yml
            preStop:
              exec:
                command:
                  - /checks/cloudzero-agent-validator
                  - diagnose
                  - pre-stop
                  - -f
                  - /checks/app/config/validator.yml
          args:
            {{ toYaml .Values.server.args | nindent 12}}
            {{- if .Values.server.agentMode }}
            - --enable-feature=agent
            {{- end }}
            - --log.level={{ .Values.server.logging.level | default "info" }}
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: {{ default 30 .Values.server.readinessProbeInitialDelay }}
            periodSeconds: {{ default 5 .Values.server.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ default 4 .Values.server.readinessProbeTimeout }}
            failureThreshold: {{ default 3 .Values.server.readinessProbeFailureThreshold }}
            successThreshold: {{ default 1 .Values.server.readinessProbeSuccessThreshold }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            initialDelaySeconds: {{ default 30 .Values.server.livenessProbeInitialDelay }}
            periodSeconds: {{ default 15 .Values.server.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ default 10 .Values.server.livenessProbeTimeout }}
            failureThreshold: {{ default 3 .Values.server.livenessProbeFailureThreshold }}
            successThreshold: {{ default 1 .Values.server.livenessProbeSuccessThreshold }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/prometheus/configmaps/
            - name: cloudzero-agent-storage-volume
              mountPath: {{ .Values.server.persistentVolume.mountPath }}
              subPath: "{{ .Values.server.persistentVolume.subPath }}"
            - name: lifecycle-volume
              mountPath: /checks/
            - name: validator-config-volume
              mountPath: /checks/app/config/
            {{- include "cloudzero-agent.apiKeyVolumeMount" . | nindent 12 }}
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        runAsGroup: 65534
        fsGroup: 65534
      {{- include "cloudzero-agent.generateDNSInfo" (dict "defaults" .Values.defaults.dns) | nindent 6 }}
      {{- include "cloudzero-agent.server.imagePullSecrets" . | nindent 6 -}}
      {{- include "cloudzero-agent.generateNodeSelector" (dict "default" .Values.defaults.nodeSelector "nodeSelector" .Values.server.nodeSelector) | nindent 6 }}
      {{- include "cloudzero-agent.generateTolerations" (concat .Values.defaults.tolerations .Values.server.tolerations) | nindent 6 }}
      {{- include "cloudzero-agent.generateAffinity" (dict "default" .Values.defaults.affinity "affinity" .Values.server.affinity) | nindent 6 }}
    {{- with .Values.server.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ default 300 .Values.server.terminationGracePeriodSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "cloudzero-agent.configMapName" . }}
        - name: validator-config-volume
          configMap:
            name: {{ template "cloudzero-agent.validatorConfigMapName" . }}
        - name: lifecycle-volume
          emptyDir: {}
        {{- if or .Values.existingSecretName .Values.apiKey }}
        - name: cloudzero-api-key
          secret:
            secretName: {{ include "cloudzero-agent.secretName" . }}
        {{- end }}
        - name: cloudzero-agent-storage-volume
        {{- if .Values.server.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.server.persistentVolume.existingClaim }}{{ .Values.server.persistentVolume.existingClaim }}{{- else }}{{ template "cloudzero-agent.server.fullname" . }}{{- end }}
        {{- else }}
          emptyDir:
          {{- if .Values.server.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.server.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end }}
        {{- end }}
