apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.configMapName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
  {{- include "cloudzero-agent.generateAnnotations" (merge .Values.defaults.annotations .Values.prometheusConfig.configMapAnnotations) | nindent 2 }}
data:
  prometheus.yml: |-
    {{- if and (not .Values.defaults.federation.enabled) .Values.prometheusConfig.configOverride }}
    {{ .Values.prometheusConfig.configOverride | nindent 4 }}
    {{- else }}
    global:
      scrape_interval: {{ .Values.prometheusConfig.globalScrapeInterval }}
    {{ if .Values.prometheusConfig.outOfOrderTimeWindow }}
    storage:
      tsdb:
        out_of_order_time_window: {{ .Values.prometheusConfig.outOfOrderTimeWindow }}
    {{- end }}

    scrape_configs:
      {{- if .Values.prometheusConfig.scrapeJobs.kubeStateMetrics.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeKubeStateMetrics" . | nindent 6 }}
      {{- end }}{{/* End kubeStateMetrics scrape job */}}

      {{- if and (not .Values.defaults.federation.enabled) .Values.prometheusConfig.scrapeJobs.cadvisor.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeCAdvisor" (dict "root" . "scrapeLocalNodeOnly" false) | nindent 6 }}
      {{- end }}{{/* End cadvisor scrape job */}}

      {{- if .Values.insightsController.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeWebhookJob" . | nindent 6 }}
      {{- end }}{{/* End webhook (insightsController) scrape job */}}

      {{- if .Values.prometheusConfig.scrapeJobs.aggregator.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeAggregator" . | nindent 6 }}
      {{- end }}{{/* End aggregator scrape job */}}

      {{- if .Values.prometheusConfig.scrapeJobs.prometheus.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapePrometheus" . | nindent 6 }}
      {{- end }}

      {{- if .Values.prometheusConfig.scrapeJobs.additionalScrapeJobs -}}
      {{ toYaml .Values.prometheusConfig.scrapeJobs.additionalScrapeJobs | toString | nindent 6 }}
      {{- end }}{{/* End additional scrape jobs */}}
    {{- end}}

    {{- include "cloudzero-agent.aggregator.remoteWrite" . | nindent 4 }}
