{{- if and .Values.rbac.create (empty .Values.server.useExistingClusterRoleName) -}}
apiVersion: {{ template "cloudzero-agent.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.components.agent.annotations
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "server"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.agent.labels
      )
    ) | nindent 2 }}
  name: {{ include "cloudzero-agent.clusterRoleName" . }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
      - "cronjobs"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - endpoints
      - namespaces
      - nodes
      {{- if not .Values.integrations.cAdvisor.directNodeAccess.enabled }}
      - nodes/proxy
      {{- end }}
      - nodes/metrics
      - services
      - pods
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "gateway.networking.k8s.io"
    resources:
      - gatewayclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{- end }}
