apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "server"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.agent.labels
      )
    ) | nindent 2 }}
  name: {{ include "cloudzero-agent.configMapName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.prometheusConfig.configMapAnnotations
        .Values.components.agent.annotations
      )
    ) | nindent 2 }}
data:
{{- if eq (include "cloudzero-agent.Values.components.agent.mode" .) "clustered" }}
  # Alloy River configuration
  alloy-config.river: |-
    {{- include "cloudzero-agent.alloy.riverConfig" . | nindent 4 }}
{{- else }}
  # Prometheus YAML configuration
  prometheus.yml: |-
    {{- if and (ne (include "cloudzero-agent.Values.components.agent.mode" .) "federated") .Values.prometheusConfig.configOverride }}
    {{ .Values.prometheusConfig.configOverride | nindent 4 }}
    {{- else }}
    global:
      scrape_interval: {{ .Values.prometheusConfig.globalScrapeInterval }}
    {{ if .Values.prometheusConfig.outOfOrderTimeWindow }}
    storage:
      tsdb:
        out_of_order_time_window: {{ .Values.prometheusConfig.outOfOrderTimeWindow }}
    {{- end }}

    scrape_configs:
      {{- if .Values.prometheusConfig.scrapeJobs.kubeStateMetrics.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeKubeStateMetrics" . | nindent 6 }}
      {{- end }}{{/* End kubeStateMetrics scrape job */}}

      {{- if and (ne (include "cloudzero-agent.Values.components.agent.mode" .) "federated") (include "cloudzero-agent.Values.integrations.cAdvisor.enabled" .) }}
      {{- include "cloudzero-agent.prometheus.scrapeCAdvisor" (dict "root" . "scrapeLocalNodeOnly" false) | nindent 6 }}
      {{- end }}{{/* End cadvisor scrape job */}}

      {{- if .Values.insightsController.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeWebhookJob" . | nindent 6 }}
      {{- end }}{{/* End webhook (insightsController) scrape job */}}

      {{- if .Values.prometheusConfig.scrapeJobs.aggregator.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeAggregator" . | nindent 6 }}
      {{- end }}{{/* End aggregator scrape job */}}

      {{- if .Values.prometheusConfig.scrapeJobs.prometheus.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapePrometheus" . | nindent 6 }}
      {{- end }}

      {{- if .Values.prometheusConfig.scrapeJobs.gpu.enabled }}
      {{- include "cloudzero-agent.prometheus.scrapeGPU" . | nindent 6 }}
      {{- end }}{{/* End GPU scrape job */}}

      {{- if .Values.prometheusConfig.scrapeJobs.additionalScrapeJobs -}}
      {{ toYaml .Values.prometheusConfig.scrapeJobs.additionalScrapeJobs | toString | nindent 6 }}
      {{- end }}{{/* End additional scrape jobs */}}
    {{- end}}

    {{- include "cloudzero-agent.aggregator.remoteWrite" . | nindent 4 }}
{{- end }}{{/* End Prometheus configuration */}}
