apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.configMapName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
  {{- include "cloudzero-agent.generateAnnotations" (merge .Values.defaults.annotations .Values.prometheusConfig.configMapAnnotations) | nindent 2 }}
data:
  prometheus.yml: |-
  {{- if .Values.prometheusConfig.configOverride }}
  {{ .Values.prometheusConfig.configOverride | nindent 4 }}
  {{- else }}
    global:
      scrape_interval: {{ .Values.prometheusConfig.globalScrapeInterval }}
    scrape_configs:
      {{- if .Values.prometheusConfig.scrapeJobs.kubeStateMetrics.enabled }}
      - job_name: static-kube-state-metrics
        honor_timestamps: true
        track_timestamps_staleness: false
        scrape_interval: {{ .Values.prometheusConfig.scrapeJobs.kubeStateMetrics.scrapeInterval }}
        scrape_timeout: 10s
        scrape_protocols:
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
        - PrometheusText0.0.4
        metrics_path: /metrics
        scheme: http
        enable_compression: true
        follow_redirects: true
        enable_http2: true
        relabel_configs:
        - separator: ;
          regex: __meta_kubernetes_service_label_(.+)
          replacement: $1
          action: labelmap
        - source_labels: [__meta_kubernetes_namespace]
          separator: ;
          regex: (.*)
          target_label: namespace
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_service_name]
          separator: ;
          regex: (.*)
          target_label: service
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: (.*)
          target_label: node
          replacement: $1
          action: replace
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).kubeMetrics }})$"
          action: keep
        - separator: ;
          regex: ^(board_asset_tag|container|created_by_kind|created_by_name|image|instance|name|namespace|node|node_kubernetes_io_instance_type|pod|product_name|provider_id|resource|unit|uid|_.*|label_.*|app.kubernetes.io/*|k8s.*)$
          replacement: $1
          action: labelkeep
        static_configs:
        - targets:
            - {{ include "cloudzero-agent.kubeStateMetrics.kubeStateMetricsSvcTargetName" . }}
      {{- end }}
      {{- if .Values.prometheusConfig.scrapeJobs.cadvisor.enabled }}
      - job_name: cloudzero-nodes-cadvisor # container_* metrics
        honor_timestamps: true
        track_timestamps_staleness: false
        scrape_interval: {{ .Values.prometheusConfig.scrapeJobs.cadvisor.scrapeInterval }}
        scrape_timeout: 10s
        scrape_protocols:
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
        - PrometheusText0.0.4
        metrics_path: /metrics
        scheme: https
        enable_compression: true
        authorization:
          type: Bearer
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        follow_redirects: true
        enable_http2: true
        relabel_configs:
        - separator: ;
          regex: __meta_kubernetes_node_label_(.+)
          replacement: $1
          action: labelmap
        - separator: ;
          regex: (.*)
          target_label: __address__
          replacement: kubernetes.default.svc:443
          action: replace
        - source_labels: [__meta_kubernetes_node_name]
          separator: ;
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
          action: replace
        - source_labels: [__meta_kubernetes_node_name]
          target_label: node
          action: replace
        metric_relabel_configs:
        - action: labelkeep
          regex: "^({{ include "cloudzero-agent.requiredMetricLabels" . }})$"
        - source_labels: [__name__]
          regex: "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).containerMetrics }})$"
          action: keep
        kubernetes_sd_configs:
        - role: node
          kubeconfig_file: ""
          follow_redirects: true
          enable_http2: true
      {{- end }}
      {{- if .Values.insightsController.enabled }}
      - job_name: cloudzero-webhook-job
        metrics_path: /metrics
        scheme: https
        enable_compression: true
        tls_config:
          insecure_skip_verify: true
        follow_redirects: true
        enable_http2: true
        kubernetes_sd_configs:
          - role: endpoints
            kubeconfig_file: ""
            follow_redirects: true
            enable_http2: true
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: keep
            regex: {{ include "cloudzero-agent.insightsController.server.webhookFullname" . }}-svc
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).insightsMetrics }})$"
            action: keep
      {{- end }}
      {{- if .Values.prometheusConfig.scrapeJobs.aggregator.enabled }}
      - job_name: cloudzero-aggregator-job
        scrape_interval: {{ .Values.prometheusConfig.scrapeJobs.prometheus.scrapeInterval }}
        kubernetes_sd_configs:
          - role: endpoints
            kubeconfig_file: ""
            follow_redirects: true
            enable_http2: true
            namespaces:
              names:
                - {{ .Release.Namespace }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: {{ include "cloudzero-agent.aggregator.name" . }}
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: port-(shipper|collector)
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: "{{ include "cloudzero-agent.generateMetricNameFilterRegex" .Values }}"
            action: keep
      {{- end }}
      {{- if .Values.prometheusConfig.scrapeJobs.prometheus.enabled }}
      - job_name: static-prometheus
        scrape_interval: {{ .Values.prometheusConfig.scrapeJobs.prometheus.scrapeInterval }}
        static_configs:
          - targets:
              - localhost:9090
        metrics_path: /metrics
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: "^({{ join "|" (include "cloudzero-agent.defaults" . | fromYaml).prometheusMetrics }})$"
            action: keep
      {{- end }}
      {{- if .Values.prometheusConfig.scrapeJobs.additionalScrapeJobs -}}
      {{ toYaml .Values.prometheusConfig.scrapeJobs.additionalScrapeJobs | toString | nindent 6 }}
      {{- end}}
  {{- end}}
    remote_write:
      - url: {{ include "cloudzero-agent.metricsDestination" . }}
        authorization:
          credentials_file: {{ include "cloudzero-agent.secretFileFullPath" . }}
        write_relabel_configs:
          - source_labels: [__name__]
            regex: "^({{ include "cloudzero-agent.combineMetrics" . }})$"
            action: keep
        metadata_config:
          send: false
