apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudzero-agent.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "server"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        (dict "prometheus.io/scrape" "true" "prometheus.io/port" "9090" "prometheus.io/path" "/metrics")
      )
    ) | nindent 2 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: http-metrics
      protocol: TCP
  selector:
    {{- include "cloudzero-agent.server.matchLabels" . | nindent 4 }}
