apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cloudzero-agent.aggregator.name" . }}
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "aggregator"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.aggregator.labels
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.components.aggregator.annotations
      )
    ) | nindent 2 }}
spec:
  selector:
    {{- include "cloudzero-agent.aggregator.matchLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.aggregator.collector.port }}
  type: ClusterIP
