{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "aggregator"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.aggregator.labels
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.secretAnnotations
        .Values.components.aggregator.annotations
      )
    ) | nindent 2 }}
  name: {{ include "cloudzero-agent.secretName" .}}
  namespace: {{ include "cloudzero-agent.namespace" . }}
data:
  {{ .Values.serverConfig.containerSecretFileName }}: {{ .Values.apiKey | toString | b64enc | quote }}
{{- end }}
