apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cloudzero-agent.aggregator.name" . }}
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "aggregator"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.aggregator.labels
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.components.aggregator.annotations
        (dict "prometheus.io/scrape" "true" "prometheus.io/port" (.Values.aggregator.collector.port | quote) "prometheus.io/path" "/metrics")
      )
    ) | nindent 2 }}
spec:
  selector:
    {{- include "cloudzero-agent.aggregator.matchLabels" . | nindent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: {{ .Values.aggregator.collector.port }}
    - name: shipper-metrics
      protocol: TCP
      port: 8081
      targetPort: {{ .Values.aggregator.shipper.port }}
  type: ClusterIP
