{{ include "cloudzero-agent.generatePodDisruptionBudget" (dict
    "component" .Values.components.aggregator
    "name" (include "cloudzero-agent.aggregator.name" .)
    "matchLabels" (include "cloudzero-agent.aggregator.matchLabels" .)
    "root" .
  ) }}
