apiVersion: v1
kind: ConfigMap
metadata:
  name: validator
data:
  script.sh: |
    set -e;
    echo 'Validation starting...';
    python -m venv /app/venv;
    export PATH='/app/venv/bin:$PATH';
    pip install -r requirements.txt;
    echo 'Running validations...';
    ./validate.sh;
    echo 'Validator finished.'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-requirements
data:
  requirements.txt: |
    requests==2.32.3

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-script
data:
  validate.sh: |
    #!/usr/bin/env python3

    import os
    import requests
    import sys
    import time
    from typing import Tuple, Dict

    def check_service_availability(url: str, key: str) -> Tuple[str, str]:
      MAX_RETRY = 6
      RETRY_INTERVAL = 30

      for _ in range(MAX_RETRY):
        try:
          response = requests.get(url)
          response.raise_for_status()
          return (key, 'success')
        except Exception as e:
          print(f'{url} not ready', file=sys.stderr)
          time.sleep(RETRY_INTERVAL)

      print(f'{key} not ready after {MAX_RETRY} retries', file=sys.stderr)
      return (key, 'failure')

    def check_kube_state_metrics() -> Tuple[str, str]:
      namespace: str = os.getenv('NAMESPACE', 'default')
      url: str = os.getenv('KMS_URL', f'http://kube-state-metrics.{namespace}.svc.cluster.local:8080/')
      return check_service_availability(url, 'has_kube_state_metrics')

    def check_external_connectivity() -> Tuple[str, str]:
      host: str = os.getenv('CZ_HOST', 'api.cloudzero.com')
      url: str = f'http://{host}'
      return check_service_availability(url, 'external_connectivity')

    validations = [
      check_external_connectivity, 
      check_kube_state_metrics, 
    ]

    def run_validations() -> Dict[str, str]:
      results: Dict[str, str] = {}
      for check in validations:
        check_name: str = check.__name__
        key, value = check()
        results[key] = value
      return results

    def must_pass(results: Dict[str, str]):
      for check, result in results.items():
        if result != 'success':
          exit(1)

    def print_results(results: Dict[str, str]) -> None:
      print('---------------------------------------------')
      print ('{:<25} {:<10}'.format('CHECK', 'RESULT'))
      for check, result in results.items():
        print('{:<25} {:<10}'.format(check, result))
      print('---------------------------------------------')

    def main():
      results = run_validations()
      
      print_results(results)

      # TODO - post results to status API endpoint
      must_pass(results)

    if __name__ == '__main__':
      main()
