{{- if and .Values.rbac.create -}}
apiVersion: {{ template "cloudzero-agent.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cloudzero-agent.serviceAccountName" . }}
    namespace: {{ include "cloudzero-agent.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudzero-agent.clusterRoleName" . }}
{{- end }}
