{{- if and .Values.rbac.create (empty .Values.server.useExistingClusterRoleName) -}}
apiVersion: {{ template "cloudzero-agent.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.clusterRoleName" . }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
      - "cronjobs"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - endpoints
      - namespaces
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{- end }}
{{- if .Values.initCertJob.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.initCertJob.clusterRoleName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    resourceNames:
      - {{ include "cloudzero-agent.insightsController.deploymentName" . }}
    verbs:
      - "get"
      - "list"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames:
      - {{ include "cloudzero-agent.tlsSecretName" . }}
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingwebhookconfigurations"
    resourceNames:
    {{- range $configType, $configs := .Values.insightsController.webhooks.configurations }}
      - {{ include "cloudzero-agent.validatingWebhookConfigName" $ }}-{{ $configType }}
    {{- end }}
    verbs:
      - get
      - list
      - patch
{{- end }}
