apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cloudzero-agent.configLoaderJobName" . }}
  namespace: {{ .Release.Namespace }}
  {{- include "cloudzero-agent.generateAnnotations" (merge
      (deepCopy .Values.defaults.annotations)
      (dict "checksum/values" (include "cloudzero-agent.configurationChecksum" .))
    ) | nindent 2 }}
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "cloudzero-agent.configLoaderJobName" . }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "cloudzero-agent.insightsController.validatorJob.matchLabels" . | nindent 8 }}
      {{- include "cloudzero-agent.generateAnnotations" .Values.defaults.annotations | nindent 6 }}
    spec:
      {{- include "cloudzero-agent.generateImagePullSecrets" (dict "root" . "image" .Values.validator.image) | nindent 6 }}
      serviceAccountName: {{ include "cloudzero-agent.serviceAccountName" . }}
      restartPolicy: OnFailure
      {{- include "cloudzero-agent.generateDNSInfo" (dict "defaults" .Values.defaults.dns) | nindent 6 }}
      {{- include "cloudzero-agent.generatePriorityClassName" .Values.defaults.priorityClassName | nindent 6 }}
      containers:
        - name: run-validator
          {{- include "cloudzero-agent.generateImage" (dict "defaults" .Values.defaults.image "image" .Values.components.agent.image "compat" .Values.validator.image) | nindent 10 }}
          env:
            {{- include "cloudzero-agent.validatorEnv" . | nindent 12 }}
          command:
            - /app/cloudzero-cluster-config
            - load
            - --account
            - "{{ include "cloudzero-agent.cleanString" .Values.cloudAccountId }}"
            - --region
            - {{ .Values.region }}
            - --cluster-name
            - {{ .Values.clusterName }}
            - --release-name
            - {{ .Release.Name }}
            - --chart-version
            - {{ .Chart.Version }}
            - --agent-version
            - "{{ (include "cloudzero-agent.versionNumber" . | fromYaml).version }}"
            - --values-file
            - /cloudzero/config/values/values.yaml
            - --config-validator
            - /cloudzero/config/validator/validator.yml
            - --config-webhook
            - {{ include "cloudzero-agent.insightsController.configurationMountPath" . }}/server-config.yaml
            - --config-aggregator
            - {{ .Values.aggregator.mountRoot }}/config/config.yml
          resources:
            {{- toYaml .Values.insightsController.resources | nindent 12 }}
          volumeMounts:
            {{- include "cloudzero-agent.apiKeyVolumeMount" . | nindent 12 }}
            - name: config-values
              mountPath: /cloudzero/config/values # values.yaml
            - name: config-volume
              mountPath: /etc/config/prometheus/configmaps/
            - name: config-validator
              mountPath: /cloudzero/config/validator # validator.yml
            - name: config-webhook
              mountPath: {{ include "cloudzero-agent.insightsController.configurationMountPath" . }} # server-config.yaml
            - name: config-aggregator
              mountPath: {{ .Values.aggregator.mountRoot }}/config # config.yaml
            - name: aggregator-persistent-storage
              mountPath: {{ .Values.aggregator.mountRoot }}/data
            {{- with .Values.insightsController.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config-values
          configMap:
            name: {{ include "cloudzero-agent.helmlessConfigMapName" . }}
        - name: config-volume
          configMap:
            name: {{ template "cloudzero-agent.configMapName" . }}
        - name: config-validator
          configMap:
            name: {{ include "cloudzero-agent.validatorConfigMapName" . }}
        - name: config-webhook
          configMap:
            name: {{ include "cloudzero-agent.webhookConfigMapName" . }}
        - name: config-aggregator
          configMap:
            name: {{ include "cloudzero-agent.aggregator.name" . }}
        {{- if or .Values.existingSecretName .Values.apiKey }}
        - name: cloudzero-api-key
          secret:
            secretName: {{ include "cloudzero-agent.secretName" . }}
        {{- end }}
        {{- with .Values.insightsController.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: aggregator-persistent-storage
          emptyDir: {}
      {{- include "cloudzero-agent.generateNodeSelector" (dict "default" .Values.defaults.nodeSelector "nodeSelector" (.Values.initBackfillJob.nodeSelector | default .Values.insightsController.server.nodeSelector)) | nindent 6 }}
      {{- include "cloudzero-agent.generateAffinity" (dict "default" .Values.defaults.affinity "affinity" .Values.insightsController.server.affinity) | nindent 6 }}
      {{- include "cloudzero-agent.generateTolerations" (concat .Values.defaults.tolerations .Values.initBackfillJob.tolerations .Values.insightsController.server.tolerations) | nindent 6 }}
