{{- if .Values.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cloudzero-agent.initJobName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudzero-agent.tags.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "cloudzero-agent.initJobName" . }}
      labels:
        {{- include "cloudzero-agent.tags.initJob.matchLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cloudzero-agent.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: start-scrape
          image: {{ .Values.initJob.image.repository }}:{{ .Values.initJob.image.tag }}
          command: ["sh", "-c"]
          args:
            - |
              while true; do
                echo "Waiting for the tags server to be ready...";
                if curl -s -o /dev/null -w "%{http_code}" -k https://{{ include "cloudzero-agent.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.tags.service.port }}/healthz | grep -q 200; then
                  echo "Server is ready, starting scrape job...";
                  curl -X POST -k https://{{ include "cloudzero-agent.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.tags.service.port }}/scrape;
                  echo "Scrape process started.";
                  break;
                fi;
                echo "No 200 response from health endpoint. Retrying in 30 seconds...";
                sleep 30;
              done
{{- end }}
