{{- if .Values.initCertJob.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "init-cert"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.miscellaneous.initCert.labels
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.components.miscellaneous.initCert.annotations
      )
    ) | nindent 2 }}
  name: {{ include "cloudzero-agent.initCertJob.clusterRoleBindingName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cloudzero-agent.initCertJob.serviceAccountName" . }}
    namespace: {{ include "cloudzero-agent.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudzero-agent.initCertJob.clusterRoleName" . }}
{{- end }}
