{{ if and .Values.insightsController.tls.useCertManager }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cloudzero-agent.issuerName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.insightsController.tls.issuer.spec }}
  {{- toYaml .Values.insightsController.tls.issuer.spec | nindent 2 }}
  {{- else }}
  selfSigned: {}
  {{- end }}
{{- end }}
