{{ if .Values.tags.webhooks.issuer.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cloudzero-agent.issuerName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- toYaml .Values.tags.webhooks.issuer.spec | nindent 2 }}
{{- end }}
