{{- if .Values.server.persistentVolume.enabled -}}
{{- if not .Values.server.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.server.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.server.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
    {{- with .Values.server.persistentVolume.labels }}
       {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "cloudzero-agent.server.fullname" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
spec:
  accessModes:
{{ toYaml .Values.server.persistentVolume.accessModes | indent 4 }}
{{- with .Values.server.persistentVolume.storageClass }}
  storageClassName: {{ . | default "" }}
{{- end }}
{{- if .Values.server.persistentVolume.volumeBindingMode }}
  volumeBindingMode: "{{ .Values.server.persistentVolume.volumeBindingMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.server.persistentVolume.size }}"
{{- if .Values.server.persistentVolume.selector }}
  selector:
  {{- toYaml .Values.server.persistentVolume.selector | nindent 4 }}
{{- end -}}
{{- if .Values.server.persistentVolume.volumeName }}
  volumeName: "{{ .Values.server.persistentVolume.volumeName }}"
{{- end -}}
{{- end -}}
{{- end -}}
