{{- if .Values.initCertJob.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.initCertJob.roleName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames:
      - {{ include "cloudzero-agent.tlsSecretName" . }}
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingwebhookconfigurations"
    resourceNames:
    {{- range $configType, $configs := .Values.insightsController.webhooks.configurations }}
      - {{ include "cloudzero-agent.validatingWebhookConfigName" $ }}-{{ $configType }}
    {{- end }}
    verbs:
      - get
      - list
      - patch
{{- end }}