{{- if .Values.createSecret -}}
{{- if not .Values.apiKey }}
{{- fail "apiKey must be provided if API key is not provided by an existing secret" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.secretName" .}}
  namespace: {{ include "cloudzero-agent.namespace" . }}
data:
  value: {{ .Values.apiKey | b64enc | quote }}
{{- end }}
