{{- if .Values.existingSecretName }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.secretName" .}}
  namespace: {{ include "cloudzero-agent.namespace" . }}
data:
  value: {{ required "An API key is required when not using an existing secret via the existingSecretName argument. Provide an API key with the apiKey argument" .Values.apiKey | b64enc | quote }}
{{- end }}