{{- if .Values.existingSecretName }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.secretName" .}}
  namespace: {{ include "cloudzero-agent.namespace" . }}
data:
  value: {{- $apiKey := .Values.apiKey | toString }}
          {{- if not (regexMatch "^[a-zA-Z0-9-_.~!*'();]+$" $apiKey) }}
          {{- fail "The provided apiKey is invalid. Check that the provided value from apiKey matches exactly what is found in the CloudZero admin page." }}
          {{- end }}
          {{ $apiKey | b64enc | quote }}
{{- end }}