{{- if .Values.useExistingSecret }}
  {{- if not .Values.secretName }}
    {{- fail "'secretName' is required when 'useExistingSecret' is set to true." }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.secretName" .}}
  namespace: {{ include "cloudzero-agent.namespace" . }}
data:
  value: {{ required "An API key is required when not using an existing secret" .Values.apiKey | b64enc | quote }}
{{- end }}