{{- if .Values.useExistingSecret }}
  {{- required "A 'secretName' is required when 'useExistingSecret' is set to true." .Values.secretName }}
  # Use the existing secret specified by the user
  apiVersion: v1
  kind: Secret
  metadata:
    labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
    name: {{ .Values.secretName }}
    namespace: {{ include "cloudzero-agent.namespace" . }}
{{- else }}
  {{- if not .Values.APIKey }}
    # No existing secret is used, and no APIKey provided, create a new secret
  apiVersion: v1
  kind: Secret
  metadata:
    labels:
      {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
    name: {{ include "cloudzero-agent.secretName" .}}
    namespace: {{ include "cloudzero-agent.namespace" . }}
  data:
    value: {{ required "An API key is required when not using an existing secret" .Values.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
