{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ template "cloudzero-agent.serviceAccountName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- if kindIs "bool" .Values.server.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.server.automountServiceAccountToken }}
{{- else if kindIs "bool" .Values.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
---
{{- if .Values.initCertJob.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  name: {{ template "cloudzero-agent.initCertJob.serviceAccountName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
{{- end }}