apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudzero-agent.serviceName" . }}
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.insightsController.service.port }}
      targetPort: 8443
      name: http
  selector:
    {{- include "cloudzero-agent.insightsController.server.matchLabels" . | nindent 4 }}
