apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
  name: {{ include "cloudzero-agent.validatorConfigMapName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
  {{- with .Values.prometheusConfig.configMapAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  validator.yml: |-
    versions:
      chart_version: {{ .Chart.Version }}
      agent_version: {{ .Values.server.image.tag }}

    logging:
      level: info
      location: ./cloudzero-agent-validator.log

    deployment:
      account_id: {{ include "cloudzero-agent.cleanString" .Values.cloudAccountId }}
      cluster_name: {{ include "cloudzero-agent.cleanString" .Values.clusterName }}
      region: {{ include "cloudzero-agent.cleanString" .Values.region }}

    cloudzero:
      host:  https://{{ include "cloudzero-agent.cleanString" .Values.host }}
      credentials_file: {{ include "cloudzero-agent.secretFileFullPath" . }}
      disable_telemetry: false

    prometheus:
      {{- if .Values.validator.serviceEndpoints.kubeStateMetrics }}
      kube_state_metrics_service_endpoint: http://{{ .Values.validator.serviceEndpoints.kubeStateMetrics }}/
      {{- else }}
      kube_state_metrics_service_endpoint: http://{{ include "cloudzero-agent.kubeStateMetrics.targetOverride" . }}
      {{- end }}
      executable: /bin/prometheus
      kube_metrics:
        {{- toYaml .Values.kubeMetrics | nindent 8 }}
      configurations:
        - /etc/prometheus/prometheus.yml
        - /etc/config/prometheus/configmaps/prometheus.yml

    diagnostics:
      stages:
        - name: pre-start
          enforce: true
          checks:
            - egress_reachable
            - api_key_valid
        - name: post-start
          enforce: false
          checks:
            - k8s_version
            - kube_state_metrics_reachable
            #- node_exporter_reachable
            - prometheus_version
            - scrape_cfg
        - name: pre-stop
          enforce: false
          checks:
