{{ if .Values.insightsController.tls.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cloudzero-agent.certificateName" . }}
  namespace: {{ .Release.Namespace }}
  {{- include "cloudzero-agent.generateLabels" (dict "globals" . "labels" .Values.commonMetaLabels) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" .Values.defaults.annotations | nindent 2 }}
spec:
  secretName: {{ include "cloudzero-agent.tlsSecretName" .}}
  secretTemplate:
    {{- include "cloudzero-agent.generateAnnotations" (merge .Values.defaults.annotations .Values.secretAnnotations) | nindent 2 }}
    labels:
      {{- include "cloudzero-agent.insightsController.labels" . | nindent 6 }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  dnsNames:
    - {{ include "cloudzero-agent.serviceName" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: {{ include "cloudzero-agent.issuerName" . }}
    kind: Issuer
{{ end }}
