{{- if .Values.initCertJob.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  name: {{ template "cloudzero-agent.initCertJob.serviceAccountName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
{{- end }}
