{{- if and .Values.insightsController.tls.secret.create .Values.insightsController.tls.enabled (not .Values.insightsController.tls.useCertManager) }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "webhook-server"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.webhookServer.labels
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.components.webhookServer.annotations
      )
    ) | nindent 2 }}
  name: {{ include "cloudzero-agent.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.insightsController.tls }}
{{- if and .crt .key }}
data:
  ca.crt: {{ .crt }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}
{{- end }}
