apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudzero-agent.serviceName" . }}
  {{- include "cloudzero-agent.generateLabels" (dict
      "root" .
      "name" "webhook-server"
      "labels" (list
        .Values.defaults.labels
        .Values.commonMetaLabels
        .Values.components.webhookServer.labels
      )
    ) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (dict
      "root" .
      "annotations" (list
        .Values.defaults.annotations
        .Values.components.webhookServer.annotations
        (dict "nginx.ingress.kubernetes.io/ssl-redirect" "false")
      )
    ) | nindent 2 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.insightsController.service.port }}
      targetPort: 8443
      name: http
      appProtocol: https
  selector:
    {{- include "cloudzero-agent.insightsController.server.matchLabels" . | nindent 4 }}
