{{ if .Values.insightsController.tls.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cloudzero-agent.certificateName" . }}
  namespace: {{ .Release.Namespace }}
  {{- include "cloudzero-agent.generateLabels" (dict "globals" . "labels" .Values.commonMetaLabels) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" (merge (deepCopy .Values.defaults.annotations) .Values.secretAnnotations) | nindent 2 }}
spec:
  secretName: {{ include "cloudzero-agent.tlsSecretName" .}}
  secretTemplate:
    labels:
      {{- include "cloudzero-agent.insightsController.labels" . | nindent 6 }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  # Because sometimes this will get rendered as `2160h` it will cause a permadiff with ArgoCD when the chart says `2160h0m0s`
  # Explicitly force it to be rendered as a non-truncatable value
  duration: 2159h59m59s # 90d
  renewBefore: 359h59m59s # 15d
  dnsNames:
    - {{ include "cloudzero-agent.serviceName" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: {{ include "cloudzero-agent.issuerName" . }}
    kind: Issuer
{{ end }}
