{{- if .Values.insightsController.enabled }}
{{- range $configType, $configs := .Values.insightsController.webhooks.configurations }}
{{- if or (index $.Values.insightsController.labels.resources $configType) (index $.Values.insightsController.annotations.resources $configType) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "cloudzero-agent.validatingWebhookConfigName" $ }}-{{ $configType }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cloudzero-agent.insightsController.labels" $ | nindent 4 }}
  annotations:
    {{- include "cloudzero-agent.webhooks.annotations" $ | nindent 4 }}
webhooks:
  - name: {{ include "cloudzero-agent.validatingWebhookName" $ }}
    namespaceSelector: {{ toYaml $.Values.insightsController.webhooks.namespaceSelector }}
    failurePolicy: Ignore
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: {{ $configs.apiGroups }}
        apiVersions: [ "v1" ]
        resources: [ {{ $configType }} ]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ $.Release.Namespace }}
        name: {{ include "cloudzero-agent.serviceName" $ }}
        path: "{{ $configs.path }}"
        port: {{ $.Values.insightsController.service.port }}
      {{- if or (and $.Values.insightsController.certificate.enabled $.Values.insightsController.issuer.enabled) (gt (len $.Values.insightsController.webhooks.caBundle) 1 ) }}
      caBundle: {{ $.Values.insightsController.webhooks.caBundle }}
      {{- end }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
{{- end }}
{{- end }}
{{- end }}