name: build-and-publish-chart

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Build Dependencies
      run: |
        helm dependency update charts/cloudzero-agent/

    - name: Update Version
      id: version
      uses: flatherskevin/semver-action@v1
      with:
        incrementLevel: patch
        source: tags

    - name: Update Chart Version
      run: |
        VERSION_LINE=$(awk '/version:/ && !done {print NR; done=1}' charts/cloudzero-agent/Chart.yaml)
        sed -i ''$VERSION_LINE's/.*/version: ${{ steps.version.outputs.nextVersion }}/' charts/cloudzero-agent/Chart.yaml
        echo "NEW_VERSION=${{ steps.version.outputs.nextVersion }}" >> $GITHUB_ENV

    - name: Package Chart
      run: |
        helm package charts/cloudzero-agent/ --destination .deploy

    - name: Commit updated Chart.yaml
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "GitHub Actions Bot"
        author_email: "actions@github.com"
        message: "Update Chart.yaml to version ${{ env.NEW_VERSION }}"
        pull: '--rebase'

    - name: Upload Chart as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: agent-chart
        path: .deploy/cloudzero-agent-${{ env.NEW_VERSION }}.tgz

    - name: Checkout GH Pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Download Chart Artifact
      uses: actions/download-artifact@v2
      with:
        name: agent-chart
        path: .

    - name: Update Index
      run: |
        helm repo index --url https://cloudzero.github.io/cloudzero-charts .

    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Clouzero Bot
        author_email: ops@cloudzero.com
        message: 'Commit for ${{ env.NEW_VERSION }}'
        add: '*'
        pull: '--rebase'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.version.outputs.nextVersion }}
        tag_name: ${{ steps.version.outputs.nextVersion }}
        files: cloudzero-agent-${{ env.NEW_VERSION }}.tgz
        make_latest: true


