name: build-and-publish-chart

on:
  push:
    branches:
      - CP-17269

jobs:
  build-and-publish-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Helm
      uses: azure/setup-helm@v3


    - name: Build Dependencies
      run: |
        helm dependency update charts/cloudzero-agent/

    - name : Update Chart Version
      run: |
        VERSION_LINE=$(awk '/version:/ && !done {print NR; done=1}' charts/cloudzero-agent/Chart.yaml)
        CURRENT_VERSION=$(awk 'NR=='$VERSION_LINE' {print $2}' charts/cloudzero-agent/Chart.yaml)
        IFS='.' read -ra VER <<< "$CURRENT_VERSION"
        ((VER[2]++))  # Increment the minor version assuming version format is x.y.z
        NEW_VERSION="${VER[0]}.${VER[1]}.${VER[2]}"
        sed -i ''$VERSION_LINE's/.*/version: '$NEW_VERSION'/' charts/cloudzero-agent/Chart.yaml
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "AGENT_NAME=cloudzero-agent-$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit updated Chart.yaml
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "GitHub Actions Bot"
        author_email: "actions@github.com"
        message: "Update Chart.yaml to version ${{ env.NEW_VERSION }}"
        path: "charts/cloudzero-agent/Chart.yaml"      

    - name: Package Chart
      run: |
        helm package charts/cloudzero-agent/ --destination .deploy

    - name: Upload Chart as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: agent-chart
        path: .deploy/cloudzero-agent-${{ env.NEW_VERSION }}.tgz

    - name: Checkout GH Pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
      
    - name: Download Chart Artifact
      uses: actions/download-artifact@v2
      with:
        name: agent-chart
        path: .

    - name: Update Index 
      run: |
        helm repo index --url https://cloudzero.github.io/cloudzero-charts .
  
    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Clouzero Bot
        author_email: ops@cloudzero.com
        message: 'Commit for ${{ env.NEW_VERSION }}' 
        add: '*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_VERSION }}
        release_name: Release ${{ env.AGENT_NAME }}
        body: 'Description of the release for ${{ env.AGENT_NAME }}'
        draft: false
        prerelease: false
        latest: true
        target_commitish: ${{ github.sha }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.AGENT_NAME }}.tgz
        asset_name: ${{ env.AGENT_NAME }}.tgz
        asset_content_type: application/octet-stream