name: Ensure no changes to Agent chart
on:
  push:
    branches-ignore:
    - develop

jobs:
  check-for-agent-chart-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Check for agent chart changes
        run: |
          if git diff --name-only origin/${{ github.event.repository.default_branch }} | grep -qE '^charts/cloudzero-agent'; then
            echo "Changes to chart/cloudzero-agent must be made in the helm/ directory of cloudzero/cloudzero-agent-validator; they will be mirrored to this repository."
            exit 1
          fi
