name: lint_chart

on: [push, pull_request]


jobs:
  has_changes:
    uses: ./.github/workflows/change_detector.yml

  lint-chart:
    runs-on: ubuntu-latest
    needs: has_changes
    permissions:
      contents: read
    steps:
      - name: Checkout
        run: |
          echo "any_changed=${{ needs.has_changes.outputs.any_changed }}"

      - name: Checkout
        if: needs.has_changes.outputs.any_changed == 'true'
        uses: actions/checkout@v4

      - name: Set up Helm
        if: needs.has_changes.outputs.any_changed == 'true'
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - name: Set up chart-testing
        if: needs.has_changes.outputs.any_changed == 'true'
        uses: helm/chart-testing-action@v2.6.1

      - name: Lint the chart
        if: needs.has_changes.outputs.any_changed == 'true'
        env:
          # Agent Chart settings (prom repo is to work around issue with chart-testing tool)
          PROM_CHART_REPO: https://prometheus-community.github.io/helm-charts
          CLUSTER_NAME: cz-node-agent-ci
          CLOUD_ACCOUNT_ID: 00000000
          CZ_API_TOKEN: 'undefined'
        run: |
          cd charts/cloudzero-agent
          helm dependency update
          ct lint --debug --charts . \
            --chart-repos=kube-state-metrics=$PROM_CHART_REPO \
            --chart-repos=prometheus-node-exporter=$PROM_CHART_REPO \
            --helm-lint-extra-args "--set=existingSecretName=api-token,clusterName=$CLUSTER_NAME,cloudAccountId=$CLOUD_ACCOUNT_ID"
