name: Release Notes Approval

# Trigger the workflow on pull request events affecting the docs/releases directory
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/releases/**'

jobs:
  release-approval:
    runs-on: ubuntu-latest
    environment: release-notes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Approve Release Notes
        run: echo "Release notes approved."
