name: test-chart
on: [push]

jobs:
  test-chart:
    runs-on: ubuntu-latest
    env:  # Define environment variables here
      NAMESPACE: monitoring
      PROM_CHART_REPO: https://prometheus-community.github.io/helm-charts
      CLUSTER_NAME: cz-node-agent-ci
      CLOUD_ACCOUNT_ID: 00000000
      CZ_API_TOKEN: ${{ secrets.CZ_API_TOKEN || 'undefined' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect if any files have changed
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true
          files: |
            **.md
            charts/**/docs/**
            charts/**/tests/**
            charts/**/src/**
            charts/**/**.yaml
      
      - name: List all changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Set up Helm
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: helm/chart-testing-action@v2.6.1

      - name: Lint the chart
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd charts/cloudzero-agent
          helm dependency update
          ct lint --debug --charts . \
            --chart-repos=kube-state-metrics=$PROM_CHART_REPO \
            --chart-repos=prometheus-node-exporter=$PROM_CHART_REPO \
            --helm-lint-extra-args "--set=existingSecretName=api-token,clusterName=$CLUSTER_NAME,cloudAccountId=$CLOUD_ACCOUNT_ID"

      - name: Create kind cluster
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: helm/kind-action@v1.10.0

      - name: Create namespace
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          kubectl create namespace $NAMESPACE

      - name: Create API Token Secret
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          kubectl create secret -n $NAMESPACE generic api-token --from-literal=value=$CZ_API_TOKEN

      - name: Install the chart
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd charts/cloudzero-agent
          helm dependency update

          ct install --debug --charts . \
            --chart-repos=kube-state-metrics=$PROM_CHART_REPO \
            --chart-repos=prometheus-node-exporter=$PROM_CHART_REPO \
            --namespace $NAMESPACE \
            --helm-extra-set-args "\
              --set=existingSecretName=api-token \
              --set=clusterName=$CLUSTER_NAME \
              --set=cloudAccountId=$CLOUD_ACCOUNT_ID \
              --set=kube-state-metrics.enabled=true \
              --set=prometheus-node-exporter.enabled=true"

      - name: Cleanup API Token secret
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          kubectl -n $NAMESPACE delete secret api-token

      - name: Cleanup namespace
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          kubectl delete namespace $NAMESPACE
        