name: test_python
on:
  push:
  pull_request:

env:
  # build docker images to the (host) local registry
  REGISTRY_LOCAL_ADDR: localhost:5000
  # k8x requires the kind container address alias (comes from the kind-action)
  REGISTRY_TEST_ADDR: kind-registry:5000
  # If we are on develop or main, use the production repository
  REGISTRY_PROD_ADDR: ghcr.io
  # image name should be prefixed with the repository name
  IMAGE_NAME: ${{ github.repository }}/cloudzero-agent-validator
  
jobs:
  # This job detects if there are any changes to allow condition testing in other jobs
  has_changes:
    uses: ./.github/workflows/change-detector.yml
  
  test_python:
    runs-on: ubuntu-latest
    needs: has_changes
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - name: SETUP - Checkout
      if: needs.has_changes.outputs.any_changed == 'true'
      uses: actions/checkout@v4

    - name: SETUP - Python ${{ matrix.python-version }}
      if: needs.has_changes.outputs.any_changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: SETUP - Display Python version
      if: needs.has_changes.outputs.any_changed == 'true'
      run: |
        python -c "import sys; print(sys.version)"

    - name: TEST - Run checks
      run: |
        cd charts/cloudzero-agent
        make check
