name: test-chart
on: [push]

jobs:
  test-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect if any files have changed
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true
          files: |
            **.md
            charts/**/docs/**
            charts/**/tests/**
            charts/**/src/**
            charts/**/**.yaml
      
      - name: List all changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Set up Helm
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: helm/chart-testing-action@v2.6.1

      - name: Lint the chart
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd charts/cloudzero-agent
          helm dependency update
          ct lint --debug --charts . \
            --chart-repos=kube-state-metrics=https://prometheus-community.github.io/helm-charts \
            --chart-repos=prometheus-node-exporter=https://prometheus-community.github.io/helm-charts \
            --helm-lint-extra-args "--set='existingSecretName=api-token,clusterName=cz-node-agent-ci,cloudAccountId=00000000'"
